 name: Unit Tests
 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'

 jobs:
   unittests:
     name: CI (${{ matrix.os }}-${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     continue-on-error: ${{ matrix.experimental }}
     timeout-minutes: 90
     strategy:
       matrix:
         os: [ubuntu-latest]
         environment-file: [.ci/37.yml, .ci/38.yml, .ci/39.yml, .ci/310.yml]
         include:
           - environment-file: ci/310.yaml
             os: macos-latest
           - environment-file: ci/310.yaml
             os: windows-latest
         experimental: [false]
     steps:
       - name: checkout repo
         uses: actions/checkout@v2
       
       - name: setup micromamba
         uses: mamba-org/provision-with-micromamba@main
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
        
       - name: reinstall access - bash
         shell: bash -l {0}
         run: pip install -e . --no-deps --force-reinstall
         if: matrix.os != 'windows-latest'
      
       - name: reinstall access - powershell
         shell: powershell
         run: pip install -e . --no-deps --force-reinstall
         if: matrix.os == 'windows-latest'
       
       - name: run pytest - bash
         shell: bash -l {0}
         run: pytest -v access --cov=access --cov-report=xml
         if: matrix.os != 'windows-latest'
       
       - name: run pytest - powershell
         shell: powershell
         run: pytest -v access --cov=access --cov-report=xml
         if: matrix.os == 'windows-latest'
       
       - name: codecov
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: access-codecov
